server:
  port: 8084
spring:
  application:
    name: credit-card-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    com.netflix.eureka: DEBUG
    com.rostik.andrusiv: INFO
