server:
  port: 8080

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
    consumer:
      group-id: orders-ms
      properties:
        spring.json.trusted.packages: com.rostik.andrusiv.core.*

order:
  events:
    topic:
      name: "orders-events"
  commands:
    topic:
      name: "order-commands"
product:
  evants:
    topic:
      name: "product-events"
  commands:
    topic:
      name: "product-commands"
payment:
  events:
    topic:
      name: "payment-events"
  commands:
    topic:
      name: "payment-commands"