server:
  port: 8089

spring:
  application:
    name: order-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
    consumer:
      group-id: orders-ms
      properties:
        spring.json.trusted.packages: com.rostik.andrusiv.core.*

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    com.netflix.eureka: DEBUG
    com.rostik.andrusiv: INFO

order:
  events:
    topic:
      name: "orders-events"
  commands:
    topic:
      name: "order-commands"
product:
  evants:
    topic:
      name: "product-events"
  commands:
    topic:
      name: "product-commands"
payment:
  events:
    topic:
      name: "payment-events"
  commands:
    topic:
      name: "payment-commands"