server:
  port: 8081

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  kafka:
    admin:
      auto-create: false
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
        allow.auto.create.topics: false
    consumer:
      group-id: products-ms
      properties:
        spring.json.trusted.packages: com.rostik.andrusiv.core.*
        allow.auto.create.topics: false

product:
  commands:
    topic:
      name: "product-commands"
  events:
    topic:
      name: "product-events"
